### ISSUE TITLE
因子继承会影响同名马娘基础值

### ISSUE THREAD

**Issue by cc004** [0999312/umapyoi#11]
如果用因子[3,0,0,0,0]和[0,3,0,0,0]配种同名马娘，第一次马娘数值为[4,4,1,1,1]，第二次为[7,7,1,1,1]

**Comment by 0999312** [comment]
请提供一下马儿跳的版本，以方便测试和修复。

**Comment by 0999312** [comment]
Fixed in 0.1.8
