### ISSUE TITLE
How to use support card ticket???

### ISSUE THREAD

**Issue by Andrew4521** [0999312/umapyoi#23]
I made support card ticket, but I can't figure out how to use it. how to use the support card ticket??

我制作了支援券，但是不知道怎么使用。 如何使用支持票？

Uma ticket can use by pedestal, but where should I use support ticket to get new support card?

Uma票可以在基座上使用，但是在哪里可以使用支持票获得新的支持卡？

**Comment by 0999312** [comment]
Use a book on an empty Umamusume Pedestal, you will get Support Album Pedestal
then use support card ticket as uma ticket.
