### ISSUE TITLE
Could you Share the Source Code of 1.20.X version??

### ISSUE THREAD

**Issue by Andrew4521** [0999312/umapyoi#25]
I'd like to add some new skills, and new support cards, But source code from github is an source code for 1.18.2 version only. Please upload an project of 1.20.X version source code If you see this message. Thank you.

我想添加一些新技能和新支持卡，但是 github 的源代码仅适用于 1.18.2 版本。 请上传1.20的项目。X版本源代码 如果你看到这个消息. 谢谢大家

**Comment by 0999312** [comment]
1.20.1 Now uploaded
