### ISSUE TITLE
1.19.4 branch has 1.18.2 source code instead of 1.19.4 version

### ISSUE THREAD

**Issue by Andrew4521** [0999312/umapyoi#26]
![image](https://github.com/0999312/umapyoi/assets/74451862/28c6e40e-d39f-4bea-87e6-f8bd34b5af97)

As you see, there's no 1.19.4 code, but 1.18.2 code in 1.19.4 branch. I hope you to change this to real 1.19.4 source code plz.

**Comment by 0999312** [comment]
Well, please wait, will be soon

**Comment by 0999312** [comment]
Sorry that confirmed 1.19.4 version's code is completely deleted since no much different with 1.20.x
I will update code for 1.18 and 1.20 soon
