### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by tuzhuyue** [0999312/umapyoi#3]
## 1.人物相关

- 1.1 所有在赛马娘企划内的马娘(有决胜服)后续都有打算制作实装吗？

## 2. 属性设定

- 2.1 育成结束的决定是有一定限制还是完全自行在殿堂决定。
- 2.2 属性的效果是否能与状态赋予的效果叠加，比如力量影响挖掘速度，那么能和带效率附魔的镐叠加吗，或者两者取最高？
- 2.3 智力对于技能成功率的影响是线性的吗，能否出现100%成功的情况。
- 2.4 马娘的初始属性只会被种马影响吗？
- 2.5 计划一只成品殿堂马需要玩家育成多长时间。
## 3.马娘与服装

- 3.1 马娘的决胜服是否限定马娘独有？可以穿其他马娘的决胜服吗。鉴于目前服饰类型就三种，是否可以认为决胜服不是限定服饰，还是限定服饰未开发？

**Comment by 0999312** [comment]
1.1 : 是的，根据情况会不断更新有决胜服的马娘。  
2.1 : 完全自行决定，但是回报根据结束时马娘之魂的属性决定。  
2.2 : 属性效果与状态效果叠加，会在部分场合考虑减少属性效果收益（例如状态效果过高的情况下）以避免**过高的属性加成**。    
2.3 : 基本线性，可以出现100%成功。（事实上，100%成功的概率通常很大）    
2.4 : 初始属性根据数据包预设的基础属性以及种马影响，全属性上限**通常**不会在因子继承之后继续提升。  
2.5 : 根据训练强度、属性上限、技能配置等决定，计划正常训练一只高强度马不会超过10个MC日。  
3.1 : 马娘的决胜服限定马娘独有。目前未开发限定服饰。
