### ISSUE TITLE
Bug: 查看无NBT的空白支援卡的工具提示导致崩溃

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [0999312/umapyoi#30]
### Describe the bug

查看无NBT的空白支援卡的工具提示导致崩溃，使用召唤基座获得的支援卡正常。

### Steps to reproduce

1. 将任意两张剩余1耐久的同稀有度支援卡通过工作台合成，以试图增加耐久度；
2. 输出栏显示该物品；
3. 将鼠标移到输出物品上，然后游戏崩溃。

执行 `/give @p umapyoi:support_card 1` 命令获得名为`空白支援卡`物品，查看其工具提示也会崩溃。

砂轮也用过，正常。

### Expected behavior

需在工具提示添加一段文本，说明该支援卡不可用。

### Versions

- OS: Windows 10
- Launcher: PCL2
- Java version: 21, Azul Systems, Inc.
- Minecraft version: 1.20.1
- Umapyoi version: 1.3.21

### Additional context

https://pastebin.com/H4JfaH7q

**Comment by 0999312** [comment]
BUG FIXED IN 1.4.25-1.20.1
