### ISSUE TITLE
Bug: 在1.20.1的mohist端使用神化和马儿蹦跳mod会导致武器攻速异常

### ISSUE THREAD

**Issue by Star-Jirachi** [0999312/umapyoi#32]
### Describe the bug

在mohist端的服务器使用神化和马儿蹦跳有时会触发BUG（玩家获得神化装备后死去或者重进服务器极大可能触发。也可能有其它触发方式，但目前没发现），导致所有武器攻速都等于玩家空手时的攻速（所有武器攻速异常，超级快）。
实测使用umapyoi-1.1.21-1.20.1.jar没事，但是使用这个版本之后的马儿蹦跳模组就会导致以上的攻速BUG（umapyoi-1.4.24-1.20.1.jar和umapyoi-1.3.21-1.20.1.jar触发了BUG，umapyoi-1.4.23-1.20.1.jar没有测试）。

在单人不会触发以上BUG。

### Steps to reproduce

1.进入服务器拿一把剑，一把斧头（斧头攻速慢，更容易发现问题）
2.将剑弄上神化属性，可以手持剑使用指令：/apoth lootify apotheosis:common
3.将服务器死亡掉落关闭，输入/kill自杀（基本100%触发BUG，如果发现下列BUG无法触发可以退出重进）
4.复活后使用斧头，可以发现攻速变得非常之快。当然不止斧头使用其它任何武器都是，攻速超级快。如果加入灾变可以使用灾变的大剑炎葬，效果更明显，攻速明显异常了。

### Expected behavior

希望之后的更新可以解决在mohist服务端的攻速异常问题。

### Screenshots

服务器触发BUG时无异常日志输出。
我后面使用了玩家属性显示的mod:
[L2 Library](https://www.mcmod.cn/class/7075.html)
发现正常时玩家的攻击速度是武器攻速，而触发BUG后攻击速度是4。
正常时：
![normal](https://github.com/0999312/umapyoi/assets/103431598/34f8f933-eeba-4e77-bc23-8195a7a31649)
触发BUG后：
![bug](https://github.com/0999312/umapyoi/assets/103431598/91a17abd-9d57-4811-8230-f0d32d7f70f8)
 

### Versions

- OS:  Windows 10
- Launcher:  PCL2
- Java version: JDK 17 (17.0.1) 
- Minecraft version: 1.20.1
- Umapyoi version: 1.4.24

**Comment by 0999312** [comment]
建议检查一下其他服务端能否复现这个BUG

**Comment by Star-Jirachi** [comment]
> 建议检查一下其他服务端能否复现这个BUG

海螺端、纯forge服务端、单人都没事，似乎只有mohist会复现

**Comment by 0999312** [comment]
> > 建议检查一下其他服务端能否复现这个BUG
> 
> 海螺端、纯forge服务端、单人都没事，似乎只有mohist会复现

请联系Mohist服务端的开发者，并附上如日志等其他相关信息。否则我们无法为其进行修复。

**Comment by Star-Jirachi** [comment]
> > > 建议检查一下其他服务端能否复现这个BUG
> > 
> > 
> > 海螺端、纯forge服务端、单人都没事，似乎只有mohist会复现
> 
> 请联系Mohist服务端的开发者，并附上如日志等其他相关信息。否则我们无法为其进行修复。
最新版Mohist端和最新版mod在一起似乎不会有这个BUG了，莫名好了。
我关了吧，感谢回复。
