### ISSUE TITLE
Bug: Talent Factor is incorrectly spelt

### ISSUE THREAD

**Issue by goldfinder** [0999312/umapyoi#33]
### Describe the bug

Title

### Steps to reproduce

Creative > Umapyoi tab > Wishes > Talent 5th from last

### Expected behavior

-

### Screenshots

![image](https://github.com/0999312/umapyoi/assets/36938094/7cd15d5f-391b-420c-80ba-2dbbde47dd55)

### Versions

- OS:  WIN10
- Launcher:  Modrinth/Forge
- Java version:  17.0.9 64b
- Minecraft version:  1.20.1
- Umapyoi version:  1.4.23

**Comment by 0999312** [comment]
BUG FIXED IN 1.4.25-1.20.1
