### ISSUE TITLE
Bug: New model crashes the game

### ISSUE THREAD

**Issue by galahadplayer** [0999312/umapyoi#36]
### Describe the bug

The new uma, Hokko Tarumea's model, will crash the game

### Steps to reproduce

Equip Hokko Tarumea's uma soul on curios slot or armor stand

### Expected behavior

.

### Screenshots

[crash-2024-06-10_17.04.35-client.txt](https://github.com/user-attachments/files/15759710/crash-2024-06-10_17.04.35-client.txt)

### Versions

OS: Windows 10
Launcher: Curseforge launcher/Forge
Java version: 17.0.8
Minecraft version: 1.20.1
Umapyoi version: 1.5.28

### Additional context

Once reproduced the bug, the world would no longer be playable. The only way to fix this is to edit the world file directly.

**Comment by 0999312** [comment]
Update MMLib to newest version.
