### ISSUE TITLE
Bug: New model crashes the game again

### ISSUE THREAD

**Issue by galahadplayer** [0999312/umapyoi#37]
### Describe the bug

Cheval Grand's model crashes the game.

### Steps to reproduce

Equip Cheval Grand's uma soul on player or armor stand or anything that do the same trick.

### Expected behavior

.

### Screenshots

[crash-2024-06-28_10.21.26-client.txt](https://github.com/user-attachments/files/16023370/crash-2024-06-28_10.21.26-client.txt)

### Versions

OS: Windows 10
Launcher: Curseforge launcher/Forge
Java version: 17.0.8
Minecraft version: 1.20.1
Forge version: 47.3.0
Umapyoi version: 1.5.29

### Additional context

Once reproduced the bug, the world would no longer be playable. The only way to fix this is to edit the world file directly.
Same as the previous bug I submitted.

**Comment by 0999312** [comment]
FIXED in 1.5.30
