### ISSUE TITLE
Bug: crash using wishs on ThreeGoddess statue

### ISSUE THREAD

**Issue by schindlershadow** [0999312/umapyoi#44]
### Describe the bug

game crashes when putting faded soul in the ThreeGoddess statue with a wish
```
java.lang.NullPointerException: Cannot invoke "net.tracen.umapyoi.item.data.DataLocation.name()" because the return value of "net.minecraft.world.item.ItemStack.get(java.util.function.Supplier)" is null
	at TRANSFORMER/umapyoi@1.0.2-1.21/net.tracen.umapyoi.container.ThreeGoddessContainer$ThreeGoddessJewelSlot.mayPlace(ThreeGoddessContainer.java:143) ~[umapyoi-1.0.2-1.21.jar%23662!/:?] {re:classloading}
```

### Steps to reproduce

place wish in ThreeGoddess statue
attempt to place faded soul in statue

### Expected behavior

no crash and soul creation

### Versions

    OS: linux
    Launcher: neoforge 21.1.42
    Java version: openjdk 21.0.4
    Minecraft version: 1.21.1
    Umapyoi version: umapyoi-1.0.2-1.21

### Additional context

https://pastebin.com/raw/yvCi4LVZ

**Comment by 0999312** [comment]
Fixed in 1.0.3
