### ISSUE TITLE
Umamusume soul causes crash

### ISSUE THREAD

**Issue by MajinThorin564** [0999312/umapyoi#5]
1. equip umamusume soul
2. equip umamusume apparel
3. take off umamusume soul
4. crash

Here is the crash report:
[crash-2022-12-26_09.19.19-client.txt](https://github.com/0999312/umapyoi/files/10300837/crash-2022-12-26_09.19.19-client.txt)

**Comment by 0999312** [comment]
Fixed in 0.0.3, Check github release.
