### ISSUE TITLE
Crash report in multiplayer

### ISSUE THREAD

**Issue by kitamunk** [0999312/umapyoi#6]
I'm having fun playing it, but I'm asking because I've run into a problem.
Multiplayer server crashes when combining Umamusume Wishes on the Three Goddesses Statue to spawn a new umamusume.
Attach the crash report URL:https://pastebin.com/na50Ufc6

This issue does not occur in single player, is multiplayer unsupported?

Sorry if it is rude or inappropriate to you, since I use the online translation site.
thank you.

**Comment by 0999312** [comment]
Bug fixed, I will update with other content.

**Comment by 0999312** [comment]
FIXED in 0.0.5
